### ISSUE TITLE
undefined method `pretty_generate' for Puppet::Pops::Loader::RubyFunctionInstantiator::JSON:Module

### ISSUE THREAD

**Issue by bastelfreak** [sensu/puppet-module-sensuclassic#24]
## Description of problem

- What did you do?
I have this module + https://github.com/jsok/puppet-vault/ in my environment. The JSON module within this module seems to conflict.

- What happened?

During a puppet run, I get the following error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `pretty_generate' for Puppet::Pops::Loader::RubyFunctionInstantiator::JSON:Module (file: /etc/puppetlabs/code/environments/production/modules/vault/manifests/config.pp, line: 30, column: 16) on node vault

```
- What did you expect to happen?

to compile into a catalog

- How can someone reproduce the problem?

It should be enough to do a `include vault` + having the sensuclassic module in the environment.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)

There is no sensu related config on the affected machine

- Is this a masterless or master based puppet setup?

master

## Platform and version information

- Your OS: Arch Linux
- Your Ruby version: 2.6.4
- Your version of Puppet: 5.5.17
- Your version of Sensu: there is no sensu installed
- Your version of this module: v3.4.0

## Anything else to add that you think will be helpful?

The vault module uses `to_json_pretty` from stdlib:
https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/functions/to_json_pretty.rb#L75

It basically calls `JSON.pretty_generate()`. That method is provided by the default json module from the ruby core lib. My guess is that the [module JSON](https://github.com/sensu/puppet-module-sensuclassic/blob/master/lib/puppet/functions/sensuclassic_sorted_json.rb#L27) overwrites the class from the core lib.

The methods `validate_keys()`, `sorted_generate()` and `sorted_pretty_generate()` should probably extend the json class or stay within the scope of this module?

**Comment by bastelfreak** [comment]
I did some further digging and I'm not 100% sure if this issue is related to this module. I had a few other environments laying around that contain the consul module before this was merged: https://github.com/solarkennedy/puppet-consul/pull/456. Puppetserver is still not really good at environment isolation.

**Comment by treydock** [comment]
@bastelfreak I opened #25 just to rule out our monkey patch.

The only environment isolation issues I've run into with Puppetserver is for custom types/providers and that was solved with generating types for each environment when r10k is run.

**Comment by bastelfreak** [comment]
Thank you very much for the patch. I am happy to test this tomorrow. R10k is called with --generate-types for each run, so types shouldn't be an issue.
